title: jtwenty documentation
description: Documentation of the jtwenty app
theme: just-the-docs

url: https://rauf-dev.github.io/docs.jtwenty

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
